name: 'actions'
on: [push]
jobs:
  Hello-Pyton:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Running Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.10'
        - run: python hello.py
        - name: push and commit
          run: |
            git add -A
            git commit -m "pushing"
            git push
