name: 'actions'
on:
  push:
    branches:
      - 'main'
jobs:
  Hello-Pyton:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Running Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.10'
        - run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            python hello.py
        - name: push and commit
          run: |
            git config --global user.email "gelargew@gmail.com"
            git config --global user.name "bot"
            git config --global pull.rebase true
            git add -A
            git commit -m "branch"
            git pull origin release
            git checkout release
            git merge main 
            git push --set-upstream origin release
